[build]
  base = "client"  # Assuming your frontend is in the 'client' directory
  publish = "build"
  command = "npm install && npm run build"

[context.production.environment]
  NODE_VERSION = "20.3.1"  # Replace this with a specific, valid Node.js version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
