[build]
  command = "npm run build"
  publish = "client/build"  # Assuming your build files are in client/build
  base = "client"  # Set this if your package.json is in the client directory

[build.environment]
  NODE_VERSION = "20.x"
